apiVersion: v1
kind: Pod
metadata:
  name: printenv
spec:
  containers:
  - name: printenv
    image: zsh
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
