apiVersion: v1
kind: Pod
metadata:
  name: uptimed
  labels:
    name: uptimed
spec:
  containers:
  - name: uptimed
    image: uptimed
    ports:
    - containerPort: 2222
    volumeMounts:
    - mountPath: /cdrom
      name: demo-volume
  volumes:
    - name: demo-volume
      emptyDir: {}
